version: "3.3"

services:
  api:
    build: .
    image: simple-node-app
    container_name: simple-node-app
    restart: unless-stopped
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    container_name: nginx-web-proxy
    restart: unless-stopped
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
